image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish
  - deploy

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script:
    - "dotnet test"
    
publish:
    stage: publish
    script:
      - "dotnet publish -c Release"
    artifacts:
      paths:
        - \Turnstyle\bin\Release\netcoreapp2.2\
        - \Turnstyle\Dockerfile
      expire_in: 1 day
