image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - "dotnet restore"
    - "dotnet build"

test:
  stage: test
  script:
    - "dotnet test"
    
publish:
  image: docker:latest
  stage: publish
  script:
      - "docker login -u Rwhytsell67@gmail.com -p ytjBdx1_tcfEqeGLv3BY $CI_REGISTRY"
      - "docker build -t $CI_REGISTRY/triumph-gaming/turnstyle:latest ." 
      - "docker push $CI_REGISTRY/triumph-gaming/turnstyle:latest"