image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - "dotnet restore"
    - "dotnet build"

test:
  stage: test
  script:
    - "dotnet test"
    
publish:
  image: docker:latest
  stage: publish
    script:
      - "cd Turnstyle"
      - "docker build -t registry.gitlab.com/triumph-gaming/turnstyle ." 
      - "docker login -u Rwhytsell67@gmail.com -p ytjBdx1_tcfEqeGLv3BY registry.gitlab.com"
      - "docker push registry.gitlab.com/triumph-gaming/turnstyle"