image: microsoft/dotnet:latest

stages:
  - build
  - test
  - deploy

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "dotnet build"

test:
  stage: test
  script:
    - "dotnet test"
    
deploy:
    stage: deploy
    script:
    - "dotnet publish -c Release"
    - "docker login -u Rwhytsell67@gmail.com -p ytjBdx1_tcfEqeGLv3BY $CI_REGISTRY"
    - "docker build -t $CI_REGISTRY/triumph-gaming/turnstyle:latest ." 
    - "docker push $CI_REGISTRY/triumph-gaming/turnstyle:latest"
